Repository codurance/site-hubspot-migration, pull requests merged in 2022-07, with the labels that each got.

#232 Feature/banner-link-interview-process
  version_control/Codurance_September2020/css/modules/banner-link.css
  version_control/Codurance_September2020/css/pages/become-a-craftsperson-v2.css
  version_control/Codurance_September2020/modules/Banner-Link.module/fields.json
  version_control/Codurance_September2020/modules/Banner-Link.module/meta.json
  version_control/Codurance_September2020/modules/Banner-Link.module/module.html
  version_control/Codurance_September2020/templates/become-a-craftsperson-v2.html
Labels: enhancement

#235 Update README.md
  README.md
Labels: documentation

#236 Feature/case-study-template/headings-anchor
  version_control/Codurance_September2020/css/modules/section-divider.css
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/modules/Section-divider.module/fields.json
  version_control/Codurance_September2020/modules/Section-divider.module/meta.json
  version_control/Codurance_September2020/modules/Section-divider.module/module.html
  version_control/Codurance_September2020/modules/secondary-menu.module/module.js
Labels: enhancement

#237 Feature/case-study-template/cta-banner-theme-section
  version_control/Codurance_September2020/images/template-previews/banner-link_section.png
  version_control/Codurance_September2020/modules/Banner-Link.module/meta.json
  version_control/Codurance_September2020/modules/Banner-Link.module/module.html
  version_control/Codurance_September2020/modules/Landing Page Modules/LP-testimonial-slider.module/meta.json
  version_control/Codurance_September2020/modules/Landing Page Modules/LP-testimonial-slider.module/module.html
  version_control/Codurance_September2020/templates/blog-index-es.html
  version_control/Codurance_September2020/templates/blog-index.html
  version_control/Codurance_September2020/templates/hub-page-template.html
  version_control/Codurance_September2020/templates/partials/author-page.html
  version_control/Codurance_September2020/templates/partials/feature-section.html
  version_control/Codurance_September2020/templates/sections/banner-link.html
  version_control/Codurance_September2020/templates/sections/testimonial-section.html
Labels: enhancement

#238 Feature/case-study-template/update-secondary-menu
  version_control/Codurance_September2020/css/modules/secondary-menu.css
  version_control/Codurance_September2020/css/modules/section-divider.css
  version_control/Codurance_September2020/modules/secondary-menu.module/fields.json
  version_control/Codurance_September2020/modules/secondary-menu.module/meta.json
  version_control/Codurance_September2020/modules/secondary-menu.module/module.html
  version_control/Codurance_September2020/templates/case-study-template-v2.html
Labels: enhancement

#240 Feature/case-study-template/stats-highlights-module
  version_control/Codurance_September2020/css/modules/section-divider.css
  version_control/Codurance_September2020/css/modules/stats-highlights.css
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/images/template-previews/text-and-highlights_section.png
  version_control/Codurance_September2020/modules/Stats-highlights.module/fields.json
  version_control/Codurance_September2020/modules/Stats-highlights.module/meta.json
  version_control/Codurance_September2020/modules/Stats-highlights.module/module.html
  version_control/Codurance_September2020/templates/sections/text-highlights.html
  version_control/Codurance_September2020/templates/sections/text-module-section.html
Labels: enhancement

#241 Update/case-study-header
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/templates/case-study-template-v2.html
Labels: enhancement

#243 Refactor conditional statement to show/hide button
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/modules/Button.module/module.html
  version_control/Codurance_September2020/templates/case-study-template-v2.html
Labels: bug
