Repository codurance/site-hubspot-migration, pull requests merged in 2022-12, with the labels that each got.

#293 Update/remove-compass-section-temporarily
  version_control/Codurance_September2020/templates/home-v2.html
  version_control/Codurance_September2020/templates/hub-page-template.html
Labels: enhancement

#294 Update/add-subtitle-to-video
  version_control/Codurance_September2020/css/modules/clickable-listing.css
  version_control/Codurance_September2020/css/pages/rainbow-roles.css
  version_control/Codurance_September2020/modules/Clickable-Listing.module/fields.json
  version_control/Codurance_September2020/modules/Clickable-Listing.module/module.html
  version_control/Codurance_September2020/modules/Clickable-Listing.module/module.js
Labels: enhancement

#295 Insights overview hotfix
  version_control/Codurance_September2020/css/modules/editors-pick.css
  version_control/Codurance_September2020/modules/Editors-Pick.module/module.html
  version_control/Codurance_September2020/modules/Recent-posts-V2.module/module.html
Labels: bug

#297 Hotfix/insights overview page
  version_control/Codurance_September2020/css/modules/editors-pick.css
  version_control/Codurance_September2020/modules/Editors-Pick.module/module.html
  version_control/Codurance_September2020/snippets/insights-overview-snippets.html
Labels: bug

#296 Format/js-files
  .gitignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  bin/generate-config.js
  package-lock.json
  package.json
  version_control/Codurance_September2020/js/cardSlider.js
  version_control/Codurance_September2020/js/custombox-modal.js
  version_control/Codurance_September2020/js/imageLoaded.js
  version_control/Codurance_September2020/js/isotope.js
  version_control/Codurance_September2020/js/isotopePackery.js
  version_control/Codurance_September2020/js/main.js
  version_control/Codurance_September2020/js/masonry.js
  version_control/Codurance_September2020/js/popper.min.js
  version_control/Codurance_September2020/modules/Accordion.module/module.js
  version_control/Codurance_September2020/modules/Advanced Banner.module/module.js
  version_control/Codurance_September2020/modules/Apply Now.module/module.js
  version_control/Codurance_September2020/modules/Careers banner.module/module.js
  version_control/Codurance_September2020/modules/Clickable-Listing.module/module.js
  version_control/Codurance_September2020/modules/Community-events-listing.module/module.js
  version_control/Codurance_September2020/modules/Crafting code banner.module/module.js
  version_control/Codurance_September2020/modules/Featured-jobs.module/module.js
  version_control/Codurance_September2020/modules/Filtered Clients.module/module.js
  version_control/Codurance_September2020/modules/Filtered-Jobs.module/module.js
  version_control/Codurance_September2020/modules/Global-Search-Input.module/module.js
  version_control/Codurance_September2020/modules/Global-Search-Results.module/module.js
  version_control/Codurance_September2020/modules/Landing Page Modules/LP-testimonial-slider.module/module.js
  version_control/Codurance_September2020/modules/Newsletter Exit Popup.module/module.js
  version_control/Codurance_September2020/modules/Our-People-Listing.module/module.js
  version_control/Codurance_September2020/modules/Profile of a Craftsperson.module/module.js
  version_control/Codurance_September2020/modules/Recent-Events-Listing.module/module.js
  version_control/Codurance_September2020/modules/Service card.module/module.js
  version_control/Codurance_September2020/modules/Service-Lines-Listing.module/module.js
  version_control/Codurance_September2020/modules/Services Media.module/module.js
  version_control/Codurance_September2020/modules/Tabber.module/module.js
  version_control/Codurance_September2020/modules/Team Member card.module/module.js
  version_control/Codurance_September2020/modules/Testimonials Slider.module/module.js
  version_control/Codurance_September2020/modules/Training section.module/module.js
  version_control/Codurance_September2020/modules/Upcoming Events Listing.module/module.js
  version_control/Codurance_September2020/modules/Video-Mosaic.module/module.js
  version_control/Codurance_September2020/modules/Videos-Filter.module/module.js
  version_control/Codurance_September2020/modules/YouTube-Video-Popup.module/module.js
  version_control/Codurance_September2020/modules/filtered-katas.module/module.js
  version_control/Codurance_September2020/modules/menu-section.module/module.js
  version_control/Codurance_September2020/modules/secondary-menu.module/module.js
  version_control/Codurance_September2020/serverless/contacts.functions/getByToken.js
  version_control/Codurance_September2020/serverless/workable.functions/fetchAllJobs.js
  yarn.lock
Labels: enhancement

#298 Insights-overview/firesidechat
  README.md
  package.json
  version_control/Codurance_September2020/css/modules/codurance-in-motion.css
  version_control/Codurance_September2020/css/modules/editors-pick.css
  version_control/Codurance_September2020/css/modules/fireside-chat-videos.css
  version_control/Codurance_September2020/css/modules/recent-posts-v2.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
  version_control/Codurance_September2020/modules/Community-events-listing.module/module.html
  version_control/Codurance_September2020/modules/Date-Picker.module/module.html
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/fields.json
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/meta.json
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.css
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.html
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.js
  version_control/Codurance_September2020/modules/Recent-Events-Listing.module/module.html
  version_control/Codurance_September2020/modules/Recent-posts-V2.module/module.html
  version_control/Codurance_September2020/modules/Services Media.module/fields.json
  version_control/Codurance_September2020/modules/Services Media.module/module.html
  version_control/Codurance_September2020/modules/Services Media.module/module.js
  version_control/Codurance_September2020/modules/Upcoming Events Listing.module/module.html
  version_control/Codurance_September2020/modules/Videos-Listing.module/module.html
  version_control/Codurance_September2020/templates/insights-overview-page.html
Labels: documentation, enhancement

#299 Hotfix/insights-overview/fireside-chats
  version_control/Codurance_September2020/css/modules/fireside-chat-videos.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
Labels: bug
