Repository codurance/site-hubspot-migration, pull requests merged in 2023-02, with the labels that each got.

#315 Remove specific Spanish notice on blog template
  version_control/Codurance_September2020/templates/blog-index-es.html
Labels: enhancement

#317 Issue316/blog-search-results/fix-duplicated-excerpts
  version_control/Codurance_September2020/modules/Global-Search-Input.module/module.html
  version_control/Codurance_September2020/templates/blog-post.html
Labels: bug

#319 Change sorting label on the Case Study cards group
  version_control/Codurance_September2020/modules/Case Study Card Collection.module/fields.json
Labels: bug

#320 Fix/newsletter-banner-layout
  version_control/Codurance_September2020/css/modules/newsletter-form-card.css
  version_control/Codurance_September2020/css/pages/blog-post.css
  version_control/Codurance_September2020/modules/Newsletter-Form-Card.module/module.html
  version_control/Codurance_September2020/templates/academy.html
  version_control/Codurance_September2020/templates/blog-post.html
  version_control/Codurance_September2020/templates/home-v2.html
  version_control/Codurance_September2020/templates/topic-pillar-page.html
Labels: bug

#323 Feature/blog-posts/custom-cta-banner
  version_control/Codurance_September2020/config/config.html
  version_control/Codurance_September2020/templates/blog-post.html
Labels: enhancement

#327 Fix newsletter block overlap with the next section
  version_control/Codurance_September2020/css/pages/topic-pillar.css
Labels: bug

#322 Update/insights overview/topics section
  version_control/Codurance_September2020/css/modules/lp-cta-block.css
  version_control/Codurance_September2020/css/modules/newsletter-form-card.css
  version_control/Codurance_September2020/css/modules/simple-card.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
  version_control/Codurance_September2020/modules/Simple-Card.module/fields.json
  version_control/Codurance_September2020/modules/Simple-Card.module/module.html
  version_control/Codurance_September2020/templates/insights-overview-page.html
  version_control/Codurance_September2020/templates/topic-pillar-page.html
Labels: enhancement

#328 Update/service-lines/what-you-gain-from-working-with-us
  version_control/Codurance_September2020/css/modules/text-and-image.css
  version_control/Codurance_September2020/css/pages/services-inner.css
  version_control/Codurance_September2020/modules/Text-and-image.module/fields.json
  version_control/Codurance_September2020/modules/Text-and-image.module/module.html
  version_control/Codurance_September2020/templates/services-inner.html
Labels: enhancement

#331 Update/replace-recent-posts-module
  version_control/Codurance_September2020/css/modules/recent-posts-v2.css
  version_control/Codurance_September2020/css/pages/newsletter-thank-you.css
  version_control/Codurance_September2020/templates/newsletter-thank-you.html
Labels: documentation

#332 Feature/module/recent-posts/filter-by-tag
  version_control/Codurance_September2020/css/pages/blog-post.css
  version_control/Codurance_September2020/modules/Recent-posts-V2.module/fields.json
  version_control/Codurance_September2020/modules/Recent-posts-V2.module/module.html
  version_control/Codurance_September2020/templates/blog-post.html
Labels: enhancement
