Repository codurance/site-hubspot-migration, pull requests merged in 2023-01, with the labels that each got.

#300 Add subtitle to section header from Fireside Chats section
  version_control/Codurance_September2020/css/_landing.css
  version_control/Codurance_September2020/css/_website.css
  version_control/Codurance_September2020/css/modules/button.css
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
  version_control/Codurance_September2020/templates/insights-overview-page.html
Labels: enhancement

#301 Allow full Youtube videos URL
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.html
Labels: bug

#302 Blog/custom-banners
  version_control/Codurance_September2020/config/config.html
  version_control/Codurance_September2020/css/modules/blog-post-banner-recruitment.css
  version_control/Codurance_September2020/css/pages/blog-post.css
  version_control/Codurance_September2020/modules/Blog Post Banner Recruitment.module/fields.json
  version_control/Codurance_September2020/modules/Blog Post Banner Recruitment.module/meta.json
  version_control/Codurance_September2020/modules/Blog Post Banner Recruitment.module/module.css
  version_control/Codurance_September2020/modules/Blog Post Banner Recruitment.module/module.html
  version_control/Codurance_September2020/modules/Blog Post Banner Recruitment.module/module.js
  version_control/Codurance_September2020/modules/Blog Post Banner.module/fields.json
  version_control/Codurance_September2020/modules/Blog Post Banner.module/meta.json
  version_control/Codurance_September2020/modules/Blog Post Banner.module/module.css
  version_control/Codurance_September2020/modules/Blog Post Banner.module/module.html
  version_control/Codurance_September2020/modules/Blog Post Banner.module/module.js
  version_control/Codurance_September2020/modules/Continue In English Blog Banner.module/module.html
  version_control/Codurance_September2020/modules/Newsletter Exit Popup.module/module.js
  version_control/Codurance_September2020/templates/blog-post.html
Labels: bug, enhancement

#303 Update/insights-overview-page/katalyst-section
  version_control/Codurance_September2020/css/_website.css
  version_control/Codurance_September2020/css/modules/random-katas.css
  version_control/Codurance_September2020/css/modules/videos-from-hubdb.css
  version_control/Codurance_September2020/css/pages/kata-post.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.css
  version_control/Codurance_September2020/modules/Fireside-Chat-Videos.module/module.js
  version_control/Codurance_September2020/modules/Random-Katas.module/fields.json
  version_control/Codurance_September2020/modules/Random-Katas.module/meta.json
  version_control/Codurance_September2020/modules/Random-Katas.module/module.html
  version_control/Codurance_September2020/modules/Videos-From-HubDB.module/fields.json
  version_control/Codurance_September2020/modules/Videos-From-HubDB.module/meta.json
  version_control/Codurance_September2020/modules/Videos-From-HubDB.module/module.html
  version_control/Codurance_September2020/templates/insights-overview-page.html
Labels: enhancement

#306 Fix videos not being ordered by date on ES version
  version_control/Codurance_September2020/modules/Videos-Listing.module/module.html
Labels: bug

#307 Update/insights/blog-search-system
  version_control/Codurance_September2020/css/modules/global-search-results.css
  version_control/Codurance_September2020/modules/Global-Search-Input.module/module.js
  version_control/Codurance_September2020/modules/Global-Search-Results.module/module.html
  version_control/Codurance_September2020/modules/Global-Search-Results.module/module.js
Labels: enhancement

#308 Update/insights-blog/cta-banners-translation
  version_control/Codurance_September2020/config/config.html
  version_control/Codurance_September2020/templates/blog-post.html
Labels: enhancement

#310 Fix buttons overflow on mobile in landing pages
  version_control/Codurance_September2020/css/layout.css
  version_control/Codurance_September2020/css/modules/button.css
Labels: bug

#311 Update/isights/upcoming-events
  version_control/Codurance_September2020/css/modules/editors-pick.css
  version_control/Codurance_September2020/css/modules/simple-card.css
  version_control/Codurance_September2020/css/templates/insights-overview.css
  version_control/Codurance_September2020/modules/Simple-Card.module/fields.json
  version_control/Codurance_September2020/modules/Simple-Card.module/meta.json
  version_control/Codurance_September2020/modules/Simple-Card.module/module.html
  version_control/Codurance_September2020/modules/Upcoming Events Listing.module/module.html
  version_control/Codurance_September2020/snippets/insights-overview-snippets.html
  version_control/Codurance_September2020/templates/insights-overview-page.html
Labels: enhancement

#314 Hotfix/testimonial-slider-not-working-properly
  version_control/Codurance_September2020/css/modules/lp-testimonial-slider.css
  version_control/Codurance_September2020/modules/Landing Page Modules/LP-testimonial-slider.module/meta.json
  version_control/Codurance_September2020/modules/Landing Page Modules/LP-testimonial-slider.module/module.js
Labels: bug
