Repository codurance/site-hubspot-migration, pull requests merged in 2023-06, with the labels that each got.

#386 Feature/nav menu/submenus promotional section
  version_control/Codurance_September2020/css/_header.css
  version_control/Codurance_September2020/css/modules/menu-section.css
  version_control/Codurance_September2020/css/pages/industries-overview.css
  version_control/Codurance_September2020/css/pages/industry.css
  version_control/Codurance_September2020/css/theme-overrides.css
  version_control/Codurance_September2020/css/utils/_card-styles.css
  version_control/Codurance_September2020/js/main.js
  version_control/Codurance_September2020/modules/menu-section.module/fields.json
  version_control/Codurance_September2020/modules/menu-section.module/meta.json
  version_control/Codurance_September2020/modules/menu-section.module/module.html
  version_control/Codurance_September2020/modules/menu-section.module/module.js
  version_control/Codurance_September2020/templates/industries-overview-page.html
  version_control/Codurance_September2020/templates/industry-page.html
  version_control/Codurance_September2020/templates/landing-page-template.html
  version_control/Codurance_September2020/templates/partials/header.html
  version_control/Codurance_September2020/templates/partials/header_landing_page.html
  version_control/Codurance_September2020/templates/system/membership-login.html
  version_control/Codurance_September2020/templates/system/membership-register.html
  version_control/Codurance_September2020/templates/system/membership-reset-password-request.html
  version_control/Codurance_September2020/templates/system/membership-reset-password.html
Labels: enhancement

#387 Rename header classes from service line header
  version_control/Codurance_September2020/css/modules/service-line-header.css
  version_control/Codurance_September2020/modules/Service-Line-header.module/module.html
Labels: bug

#392 Fix/navigation-menu/screen-resizing
  version_control/Codurance_September2020/css/modules/utilities-menu.css
  version_control/Codurance_September2020/js/main.js
Labels: bug, enhancement

#396 Update/old-landing-pages-template/configurable-background
  version_control/Codurance_September2020/css/pages/promotional-landing.css
  version_control/Codurance_September2020/templates/promotional-landing-page.html
Labels: enhancement

#397 Set background image to cover landing page
  version_control/Codurance_September2020/css/pages/promotional-landing.css
  version_control/Codurance_September2020/templates/promotional-landing-page.html
Labels: enhancement

#398 Feature/main-navigation-menu/search-bar
  version_control/Codurance_September2020/css/_header.css
  version_control/Codurance_September2020/css/modules/global-search-input.css
  version_control/Codurance_September2020/css/modules/language-selector.css
  version_control/Codurance_September2020/css/modules/menu-section.css
  version_control/Codurance_September2020/css/modules/navigation-link.css
  version_control/Codurance_September2020/css/partials/utilities-menu.css
  version_control/Codurance_September2020/js/partials/utilities-menu.js
  version_control/Codurance_September2020/modules/Global-Search-Input.module/module.html
  version_control/Codurance_September2020/modules/Global-Search-Input.module/module.js
  version_control/Codurance_September2020/modules/Global-Search-Results.module/module.html
  version_control/Codurance_September2020/modules/Global-Search-Results.module/module.js
  version_control/Codurance_September2020/modules/Language-Selector.module/fields.json
  version_control/Codurance_September2020/modules/Language-Selector.module/meta.json
  version_control/Codurance_September2020/modules/Language-Selector.module/module.html
  version_control/Codurance_September2020/modules/Navigation-Link.module/fields.json
  version_control/Codurance_September2020/modules/Navigation-Link.module/meta.json
  version_control/Codurance_September2020/modules/Navigation-Link.module/module.html
  version_control/Codurance_September2020/modules/Utilities-Menu.module/meta.json
  version_control/Codurance_September2020/modules/Utilities-Menu.module/module.html
  version_control/Codurance_September2020/templates/partials/header.html
  version_control/Codurance_September2020/templates/partials/utilities-menu.html
  version_control/Codurance_September2020/templates/system/search-results.html
Labels: enhancement

#390 Configure npm scripts to work along Katalyst
  package.json
Labels: enhancement
