Repository codurance/site-hubspot-migration, pull requests merged in 2023-10, with the labels that each got.

#423 Change aspect ratio image on blog author images
  version_control/Codurance_September2020/css/pages/blog-post.css
Labels: bug

#427 Create conditional to hide default pop-up newsletter banner
  version_control/Codurance_September2020/templates/blog-post.html
Labels: enhancement

#428 New-module/contact-us-page/office-listing
  version_control/Codurance_September2020/css/_website.css
  version_control/Codurance_September2020/css/modules/offices-listing.css
  version_control/Codurance_September2020/css/pages/contact-us.css
  version_control/Codurance_September2020/modules/Offices-Listing.module/fields.json
  version_control/Codurance_September2020/modules/Offices-Listing.module/module.html
  version_control/Codurance_September2020/templates/contact-us.html
Labels: enhancement

#429 Fix/contact-us/page-adjustments
  version_control/Codurance_September2020/css/modules/offices-listing.css
  version_control/Codurance_September2020/css/pages/contact-us.css
  version_control/Codurance_September2020/modules/Offices-Listing.module/fields.json
  version_control/Codurance_September2020/modules/Offices-Listing.module/module.html
Labels: bug, enhancement

#430 Fix font weight offices address on contact us
  version_control/Codurance_September2020/css/modules/offices-listing.css
Labels: bug
