Repository codurance/site-hubspot-migration, pull requests merged in 2023-04, with the labels that each got.

#347 feature: increment the maximum amount of rainbow roles
  version_control/Codurance_September2020/modules/Clickable-Listing.module/fields.json
Labels: enhancement

#350 Fix/dnd-spacing
  version_control/Codurance_September2020/css/modules/case-study-card.css
  version_control/Codurance_September2020/css/pages/topic-pillar.css
  version_control/Codurance_September2020/css/theme-overrides.css
  version_control/Codurance_September2020/fields.json
  version_control/Codurance_September2020/templates/sections/testimonial-section.html
Labels: enhancement, request

#354 Feature/industries/secondary-clients-cards
  version_control/Codurance_September2020/css/_landing.css
  version_control/Codurance_September2020/css/_website.css
  version_control/Codurance_September2020/css/base/_layout-2021.css
  version_control/Codurance_September2020/css/modules/case-study-card.css
  version_control/Codurance_September2020/css/modules/secondary-clients-cards.css
  version_control/Codurance_September2020/css/pages/case-study-template-v2.css
  version_control/Codurance_September2020/css/pages/homepage.css
  version_control/Codurance_September2020/css/pages/privacy-policy.css
  version_control/Codurance_September2020/css/partials/partners-section.css
  version_control/Codurance_September2020/modules/Case Study Card Collection.module/module.html
  version_control/Codurance_September2020/modules/Secondary-Clients-Cards.module/fields.json
  version_control/Codurance_September2020/modules/Secondary-Clients-Cards.module/meta.json
  version_control/Codurance_September2020/modules/Secondary-Clients-Cards.module/module.html
Labels: enhancement

#348 Translations to pt
  version_control/Codurance_September2020/config/config.html
  version_control/Codurance_September2020/modules/Date-Picker.module/module.html
  version_control/Codurance_September2020/modules/Featured-jobs.module/module.html
  version_control/Codurance_September2020/modules/Filtered-Jobs.module/module.js
  version_control/Codurance_September2020/modules/Interview Process.module/module.html
  version_control/Codurance_September2020/modules/Newsletter Exit Popup.module/module.html
  version_control/Codurance_September2020/modules/Newsletter Footer Form.module/module.html
  version_control/Codurance_September2020/modules/Recent-Events-Listing.module/module.html
  version_control/Codurance_September2020/modules/Simple-Card.module/module.html
  version_control/Codurance_September2020/modules/Videos-Filter.module/module.html
  version_control/Codurance_September2020/modules/Videos-Listing.module/module.html
  version_control/Codurance_September2020/templates/blog-index-pt.html
  version_control/Codurance_September2020/templates/blog-post.html
  version_control/Codurance_September2020/templates/landing-page-template.html
  version_control/Codurance_September2020/templates/landing-page-with-menu.html
  version_control/Codurance_September2020/templates/newsletter-sign-up.html
  version_control/Codurance_September2020/templates/partials/footer.html
  version_control/Codurance_September2020/templates/partials/header.html
Labels: enhancement

#360 Upgrade serverless functions to Node 18 version
  .github/workflows/deploy-staging.yml
  .github/workflows/deploy.yml
  version_control/Codurance_September2020/serverless/contacts.functions/serverless.json
  version_control/Codurance_September2020/serverless/workable.functions/serverless.json
Labels: bug

#359 Update/partners-section
  version_control/Codurance_September2020/css/modules/partner-logos.css
  version_control/Codurance_September2020/modules/Partner-Logos.module/module.html
Labels: enhancement

#357 Create/industries/overview
  version_control/Codurance_September2020/css/base/_layout-2021.css
  version_control/Codurance_September2020/css/modules/case-study-card.css
  version_control/Codurance_September2020/css/modules/text-and-image.css
  version_control/Codurance_September2020/css/modules/text-image-default.css
  version_control/Codurance_September2020/css/modules/thumbnails-grid.css
  version_control/Codurance_September2020/css/pages/industries-overview.css
  version_control/Codurance_September2020/css/pages/industry.css
  version_control/Codurance_September2020/css/pages/job-listing-page.css
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/_locales/en/messages.json
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/_locales/es/messages.json
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/_locales/pt/messages.json
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/fields.json
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/meta.json
  version_control/Codurance_September2020/modules/Thumbnails-Grid.module/module.html
  version_control/Codurance_September2020/templates/industries-overview-page.html
  version_control/Codurance_September2020/theme.json
Labels: enhancement

#361 Fix/industries-header
  version_control/Codurance_September2020/css/modules/text-and-image.css
  version_control/Codurance_September2020/css/pages/industries-overview.css
  version_control/Codurance_September2020/templates/industries-overview-page.html
Labels: enhancement

#362 Remove temporary breadcrumbs blocking style on industry pages
  version_control/Codurance_September2020/css/pages/industry.css
Labels: enhancement

#365 Adjust form styling to avoid messages overflowing
  version_control/Codurance_September2020/css/modules/newsletter-form-card.css
  version_control/Codurance_September2020/templates/academy.html
Labels: bug

#363 Update/module/text-and-image-spacing-config
  version_control/Codurance_September2020/css/base/_buttons.css
  version_control/Codurance_September2020/css/modules/text-and-image.css
  version_control/Codurance_September2020/css/pages/become-a-craftsperson-v2.css
  version_control/Codurance_September2020/css/pages/careers-v2.css
  version_control/Codurance_September2020/css/pages/clients.css
  version_control/Codurance_September2020/css/pages/homepage-v2.css
  version_control/Codurance_September2020/css/pages/industries-overview.css
  version_control/Codurance_September2020/css/pages/industry.css
  version_control/Codurance_September2020/css/pages/interview-overview.css
  version_control/Codurance_September2020/css/pages/topic-pillar.css
  version_control/Codurance_September2020/modules/Text-and-image.module/fields.json
  version_control/Codurance_September2020/templates/become-a-craftsperson-v2.html
  version_control/Codurance_September2020/templates/careers-v2.html
  version_control/Codurance_September2020/templates/clients.html
  version_control/Codurance_September2020/templates/home-v2.html
  version_control/Codurance_September2020/templates/interview-overview.html
  version_control/Codurance_September2020/templates/topic-pillar-page.html
Labels: enhancement, request

#367 Set up image alignment dependant on viewpoint
  version_control/Codurance_September2020/modules/Text-and-image.module/fields.json
  version_control/Codurance_September2020/modules/Text-and-image.module/module.html
Labels: enhancement

#368 Update/blog-author-page/format-cards-correctly
  version_control/Codurance_September2020/css/base/_layout-2021.css
  version_control/Codurance_September2020/css/pages/blog-index.css
  version_control/Codurance_September2020/css/partials/author-page.css
  version_control/Codurance_September2020/css/partials/social-icons.css
  version_control/Codurance_September2020/css/utils/_card-styles.css
  version_control/Codurance_September2020/templates/blog-index.html
  version_control/Codurance_September2020/templates/partials/author-page.html
Labels: enhancement, request

#373 Adjust gutters from ES and PT blog listing pages
  version_control/Codurance_September2020/templates/blog-index-es.html
  version_control/Codurance_September2020/templates/blog-index-pt.html
Labels: bug

#375 Fix bug blurring the text middle on read more
  version_control/Codurance_September2020/modules/Service-Lines-Listing.module/module.html
Labels: bug
